# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\joystick_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.back_frame = QtWidgets.QFrame(self.centralwidget)
        self.back_frame.setMinimumSize(QtCore.QSize(360, 480))
        self.back_frame.setMaximumSize(QtCore.QSize(360, 480))
        self.back_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back_frame.setObjectName("back_frame")
        self.joy_outside = QtWidgets.QFrame(self.back_frame)
        self.joy_outside.setGeometry(QtCore.QRect(90, 230, 180, 180))
        self.joy_outside.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joy_outside.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joy_outside.setObjectName("joy_outside")
        self.joystick = QtWidgets.QLabel(self.back_frame)
        self.joystick.setGeometry(QtCore.QRect(40, 30, 281, 41))
        self.joystick.setAlignment(QtCore.Qt.AlignCenter)
        self.joystick.setObjectName("joystick")
        self.joy_inside = QtWidgets.QFrame(self.back_frame)
        self.joy_inside.setGeometry(QtCore.QRect(135, 275, 90, 90))
        self.joy_inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.joy_inside.setFrameShadow(QtWidgets.QFrame.Raised)
        self.joy_inside.setObjectName("joy_inside")
        self.widget = QtWidgets.QWidget(self.back_frame)
        self.widget.setGeometry(QtCore.QRect(40, 110, 281, 51))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.linear_speed = QtWidgets.QLabel(self.widget)
        self.linear_speed.setObjectName("linear_speed")
        self.gridLayout.addWidget(self.linear_speed, 0, 0, 1, 1)
        self.lin_speed_value = QtWidgets.QLabel(self.widget)
        self.lin_speed_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lin_speed_value.setObjectName("lin_speed_value")
        self.gridLayout.addWidget(self.lin_speed_value, 0, 1, 1, 1)
        self.ang_speed_value = QtWidgets.QLabel(self.widget)
        self.ang_speed_value.setAlignment(QtCore.Qt.AlignCenter)
        self.ang_speed_value.setObjectName("ang_speed_value")
        self.gridLayout.addWidget(self.ang_speed_value, 1, 1, 1, 1)
        self.angular_speed = QtWidgets.QLabel(self.widget)
        self.angular_speed.setObjectName("angular_speed")
        self.gridLayout.addWidget(self.angular_speed, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.back_frame, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.joystick.setText(_translate("MainWindow", "JOYSTICK"))
        self.linear_speed.setText(_translate("MainWindow", "Linear Speed:"))
        self.lin_speed_value.setText(_translate("MainWindow", "0"))
        self.ang_speed_value.setText(_translate("MainWindow", "0"))
        self.angular_speed.setText(_translate("MainWindow", "Angular Speed:"))
        self.label.setText(_translate("MainWindow", "m/s"))
        self.label_2.setText(_translate("MainWindow", "rad/s"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
